name: Test Project

on: workflow_dispatch

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Execute Gradle Build
        run: ./gradlew build
        
      - name: Run unit tests
        run: ./gradlew test --stacktrace